## Estadistica Aplicada
Sesión 2 - 9 agosto

Joel Fayam Rivera Peña 2076323

Una lista en Python es una colección de objetos que pueden ser de distinto tipo.

In [1]:
alumno1=['Juan','Perez',17]

In [2]:
type(alumno1)

list

In [3]:
alumno1

['Juan', 'Perez', 17]

In [4]:
estadistica_g4=['Dania','Karla','Alan','Vania']

In [5]:
estadistica_g4

['Dania', 'Karla', 'Alan', 'Vania']

In [7]:
estadistica_g4[2]

'Alan'

In [8]:
estadistica_g4[0]

'Dania'

In [11]:
estadistica_g4[0], estadistica_g4[2]

('Dania', 'Alan')

In [18]:
estadistica_g4[0:3]

['Dania', 'Karla', 'Alan']

In [13]:
yo_en_FCFM=['Joel','LA',7,90]

In [16]:
mi_promedio=yo_en_FCFM[3]
mi_carrera=yo_en_FCFM[1]

In [19]:
print(mi_carrera,mi_promedio)

LA 90


## Librerías / Modulos / paquetes

Una librería, o un modulo, en Python es un conjunto de códigos que le dice a Python como hacer determinadas cosas

Una librería primero se instala (única vez), y luego se le indica a python que la use

In [29]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [25]:
import yfinance as yf

In [ ]:
yf.download()

# Numpy

Numpy nos sirve para manejar números en Python

In [31]:
import numpy as np

La estructura básica de numpy son los arreglos (arrays), que son una colección de objetos del mismo tipo (numéricos)

In [32]:
# crear la lista con las ventas de paleta en la cafeteria
ventas=[12,23,34,45,56]

In [34]:
ventas=np.array(ventas)

In [35]:
type(ventas)

numpy.ndarray

In [40]:
# promedio
np.mean(ventas)

34.0

In [41]:
# suma
np.sum(ventas)

170

In [42]:
# maximo
np.max(ventas)

56

In [43]:
# minimo
np.min(ventas)

12

In [44]:
# Varianza poblacional
np.var(ventas)

242.0

In [46]:
# ddof implica si queremos la varianza poblacional y muestral. Si ddof=0, toma la poblacional. Si ddof=1, sería la muestral
np.var(ventas,ddof=1)

302.5

In [47]:
# desviacion
np.std(ventas)

15.556349186104045

In [48]:
np.std(ventas, ddof=1)

17.392527130926087

## Vector con Numpy

In [50]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [51]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [52]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [57]:
np.full(11,6)
# Primero se deterimna la cantidad y luego el número que queremos

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [60]:
#Semilla (siempre genera los mismos aleatorios)
np.random.seed(12)
#Aleatorios en un intervalo 0-20 con n=10
aleatorios=np.random.randint(0,20,10)

In [61]:
aleatorios

array([11,  6, 17,  2,  3,  3, 12, 16, 17,  5])

In [64]:
#Sort ordena valores de menor a mayor
aleatorios=np.sort(aleatorios)

In [66]:
aleatorios

array([ 2,  3,  3,  5,  6, 11, 12, 16, 17, 17])

In [67]:
aleatorios[4]

6

In [69]:
#El primer corchete es de selección
#El segundo corchete es la lista de posiciones
aleatorios[[0,4]]

array([2, 6])

In [72]:
#Seleccionar con condicionales
aleatorios[aleatorios>10]

array([11, 12, 16, 17, 17])

In [74]:
aleatorios[aleatorios<7]

array([2, 3, 3, 5, 6])

In [75]:
numeros=[1.2,2.34,5.18]

1.- Volverlo arreglo
2.- Calcular la media
3.- Redondear a 2 decimales la media

In [76]:
# Función
round(np.mean(np.array(numeros)),2)

2.91

In [77]:
# Metodo
np.array(numeros).mean().round(2)

2.91